# Generated by Django 5.0.6 on 2024-06-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_mri', models.ImageField(upload_to='predictions/')),
                ('generated_ct', models.ImageField(upload_to='predictions/')),
                ('reconstructed_mri', models.ImageField(upload_to='predictions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
