# Generated by Django 5.0.6 on 2024-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mriCT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprediction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='imageprediction',
            name='generated_mri',
            field=models.ImageField(blank=True, null=True, upload_to='predictions/'),
        ),
        migrations.AddField(
            model_name='imageprediction',
            name='original_ct',
            field=models.ImageField(blank=True, null=True, upload_to='predictions/'),
        ),
        migrations.AddField(
            model_name='imageprediction',
            name='reconstructed_ct',
            field=models.ImageField(blank=True, null=True, upload_to='predictions/'),
        ),
        migrations.AlterField(
            model_name='imageprediction',
            name='generated_ct',
            field=models.ImageField(blank=True, null=True, upload_to='predictions/'),
        ),
        migrations.AlterField(
            model_name='imageprediction',
            name='original_mri',
            field=models.ImageField(blank=True, null=True, upload_to='predictions/'),
        ),
        migrations.AlterField(
            model_name='imageprediction',
            name='reconstructed_mri',
            field=models.ImageField(blank=True, null=True, upload_to='predictions/'),
        ),
    ]
